<!DOCTYPE html>
<html>
<head>
<title>Thông báo</title>
</head>
<body>
<h3>Xin chào ${name}!, <br>BKHcare xin cảm ơn bạn đã tin tưởng và sử dụng đặt lịch khám bệnh trên app BKHcare!</h3>
	<p>BKHcare xin thông báo bạn đang yêu cầu reset mật khẩu mới</p> <br/>
	<p>Hãy nhập mã OTP sau để tiến hành reset mật khẩu</p> <br/>

<p >Mã OTP của bạn là : <p style="font-size:24px;color:blue"> ${otp}</p> </p>
	<p>Một lần nữa xin cảm ơn bạn đã tin dùng !</p>
</body>
</html>