<!DOCTYPE html>
<html>
<head>
<title>Thông báo</title>
</head>
<body>
<h3>Xin chào ${name}!, <br>BKHcare xin cảm ơn bạn đã tin tưởng và sử dụng đặt lịch khám bệnh trên app BKHcare!</h3>
	<p>BKHcare xin thông báo bạn đang yêu cầu reset mật khẩu mới</p> <br/>
	<p>Cick vào đường link sau đây để tiến hành đổi mật khẩu</p> <br/>
<a style="color:blue" href=`${direct_url}`><u> Change my password </u></a></p> <br/>
	<p>Một lần nữa xin cảm ơn bạn đã tin dùng !</p>
</body>
</html>